### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by dufferzafar** [lervag/apy#10]
Running `apy --info` works. So all the `anki` related modules have been loaded correctly.

But when running `apy info` I get a config file not found error. Going through the readme, it felt as in the config file is optional. Is that not the case?

```pytb
Config file:             Not found
Traceback (most recent call last):
  File "/home/dufferzafar/.local/bin/apy", line 11, in <module>
    load_entry_point('apy==0.1', 'console_scripts', 'apy')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/apy/cli.py", line 147, in info
    with Anki(cfg['base']) as a:
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/apy/anki.py", line 28, in __init__
    self._init_load_collection(base, path)
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/apy/anki.py", line 47, in _init_load_collection
    basepath = Path(base)
  File "/usr/lib/python3.8/pathlib.py", line 1033, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by dufferzafar** [comment]
So, I copied the config file as it is from the readme. Got a new error:


```pytb

Config file:             /home/dufferzafar/.config/apy/apy.json
Config loaded:           pngCommands
Config loaded:           svgCommands
Config loaded:           base
Config loaded:           width
Traceback (most recent call last):
  File "/home/dufferzafar/.local/bin/apy", line 11, in <module>
    load_entry_point('apy==0.1', 'console_scripts', 'apy')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/apy/cli.py", line 147, in info
    with Anki(cfg['base']) as a:
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/apy/anki.py", line 28, in __init__
    self._init_load_collection(base, path)
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/apy/anki.py", line 47, in _init_load_collection
    basepath = Path(base)
  File "/usr/lib/python3.8/pathlib.py", line 1033, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

Looks like, I'll tk

**Comment by lervag** [comment]
Thanks! I'll look into this asap (tonight or tomorrow night).

**Comment by dufferzafar** [comment]
If I don't create a PR before then :stuck_out_tongue:

**Comment by lervag** [comment]
> If I don't create a PR before then

That would be even better! :)

**Comment by dufferzafar** [comment]
Well, this is just a documentation issue (IMO)

I opened `cli.py` and it was obvious that I had to specify the `base` Anki directory.

`apy -b ~/.local/share/Anki2 info` worked!

**Comment by dufferzafar** [comment]
BTW, the code is very well documented, so props to that!

**Comment by dufferzafar** [comment]
Setting `base` to `"~/.local/share/Anki2"` didn't work, because the code doesn't `os.expanduser`

**Comment by lervag** [comment]
> `apy -b ~/.local/share/Anki2 info` worked!

Ah, yes, of course. I didn't read the error well enough. So, I would claim it is not just a configuration issue! The error message should be clearer in this case!

> BTW, the code is very well documented, so props to that!

Thanks!

> Setting base to `~/.local/share/Anki2` didn't work, because the code doesn't `os.expanduser`.

You're right. Also a point that can be improved!

So, summarized list of TODOs:
- [ ] Improve error message when the base path is not recognized/valid.
- [ ] Use `os.expanduser` (and perhaps more expands) for the base path in the config file.
- [ ] Possibly improve documentation

**Comment by lervag** [comment]
I've fixed the issues mentioned here now. Do you have any suggestions for how to improve the docs? I.e., what is missing/what should be improved?

**Comment by dufferzafar** [comment]
I think just printing an error message when base path isn't set should be enough!

**Comment by lervag** [comment]
In other words, that the current issue is fully resolved?

**Comment by dufferzafar** [comment]
Yeah, this is done! thanks!
