### ISSUE TITLE
AttributeError: '_Collection' object has no attribute 'sched_ver'. Did you mean: 'schedVer'?

### ISSUE THREAD

**Issue by fugohan** [lervag/apy#47]
Fresh install of Ubuntu 22.04 
With Anki 2.1.52-linux-qt6
APY latest version installed

```
apy -b /home/docker/.local/share/Anki2/
Config file:             Not found
Collecton path:          /home/docker/.local/share/Anki2/edyn/collection.anki2
Traceback (most recent call last):
  File "/home/docker/.local/bin/apy", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/docker/.local/lib/python3.10/site-packages/apy/cli.py", line 54, in main
    ctx.invoke(info)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/docker/.local/lib/python3.10/site-packages/apy/cli.py", line 183, in info
    click.echo(f"Scheduler version:       {a.col.sched_ver()}")
AttributeError: '_Collection' object has no attribute 'sched_ver'. Did you mean: 'schedVer'?
```

**Comment by lervag** [comment]
Strange. I'm quite sure that the error is due to you using an old version of Anki. You claim 2.1.52, but notice:

https://github.com/ankitects/anki/blob/2.1.52/pylib/anki/collection.py#L171

I.e., in the source code for the python lib of Anki, the function _is_ called `sched_ver`. This is one of only a few updates the last year that I had to make in order to support the newer versions of Anki.

Can you investigate if you by chance have several Anki versions installed, or perhaps some left overs from previous versions?

**Comment by fugohan** [comment]
After a fresh install of Ubuntu in a VM with these steps I get this error. (binary install) 

```
wget https://github.com/ankitects/anki/releases/download/2.1.52/anki-2.1.52-linux-qt6.tar.zst

tar xaf anki-2.1.52-linux-qt6.tar.zst
cd anki-2.1.52-linux-qt6
sudo ./install.sh
sudo apt install python3-pip -y

#latest version
pip install --user git+https://github.com/lervag/apy.git#egg=apy
PATH=/home/user/.local/bin:$PATH
```




```
apy
Traceback (most recent call last):
  File "/home/user/.local/bin/apy", line 5, in <module>
    from apy.cli import main
  File "/home/user/.local/lib/python3.10/site-packages/apy/cli.py", line 8, in <module>
    from apy.anki import Anki
  File "/home/user/.local/lib/python3.10/site-packages/apy/anki.py", line 7, in <module>
    import anki
ModuleNotFoundError: No module named 'anki'
```


second try: 

```
sudo apt install git anki python3-pip -y
#latest version
pip install --user git+https://github.com/lervag/apy.git#egg=apy
PATH=/home/user/.local/bin:$PATH
``` 

I get this Error message (again): 

````
apy -b ~/.local/share/Anki2/
Config file:             Not found
Collecton path:          /home/user/.local/share/Anki2/User 1/collection.anki2
Traceback (most recent call last):
  File "/home/user/.local/bin/apy", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/apy/cli.py", line 54, in main
    ctx.invoke(info)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/apy/cli.py", line 183, in info
    click.echo(f"Scheduler version:       {a.col.sched_ver()}")
AttributeError: '_Collection' object has no attribute 'sched_ver'. Did you mean: 'schedVer'?

````

How can I install a newer version of Anki on Ubuntu? (via apk I get 2.1.15)

**Comment by lervag** [comment]
> How can I install a newer version of Anki on Ubuntu? (via apk I get 2.1.15)

That's the question :)

From the README:

> `apy` assumes that the Anki source is available at `/usr/share/anki`. If you put it somewhere else, then you must set the environmen variable `APY_ANKI_PATH`, e.g. `export APY_ANKI_PATH=/my/path/to/anki`.

I have to admit I am not entirely sure. I believe you do not get the proper source files with the release zips. Perhaps it suffices to download the Anki source and use the `APY_ANKI_PATH`?

**Comment by fugohan** [comment]
What do you mean with the proper source files? Should I clone Anki from github and compile it myself? Is apy compatible with the current version of Anki?

**Comment by lervag** [comment]
Sorry about the late reply, was travelling.

> Is apy compatible with the current version of Anki?

Yes! The compatibility is explained in the README.

> What do you mean with the proper source files? Should I clone Anki from github and compile it myself?

I mean that the way `apy` works is that it relies on the Anki codebase itself, directly. That is, on the Python APIs - much of the real work in Anki has been moved into a Rust backend. But for `apy` to work, we need to have the Python libraries for Anki available. These are however _not_ shipped with the standard packaged releases.

I'll try and make a Docker image with Ubuntu 22.04 to test this myself with a Ubuntu based distro. I'll let you know how you can make it work when I've figured it out.

**Comment by lervag** [comment]
I've updated the install instructions - I believe the new instructions should work and are more helpful. Could you read it and try?

**Comment by fugohan** [comment]
Yeah its working. Thank you, great work!

**Comment by lervag** [comment]
Great, glad to hear it! :)
