### ISSUE TITLE
Bug: chosen model (note type) does not override last active model. 

### ISSUE THREAD

**Issue by skervim** [lervag/apy#7]
I realized that there is apparently still a problem with the selection of the note type. 
Let's say, I open anki desktop and add a card of note type "A" to a deck and close it.
Then I try to add a new card with `apy add` or `apy add-from-file` of a __different__ note type "B".
Here, if the note types have a different number of fields, the following error will occur (if they have the same number of fields, still the old note type "A" will be chosen and populated with the chosen field values):
```
Traceback (most recent call last):
  File "/home/skervim/anaconda3/envs/rl/bin/apy", line 11, in <module>
    load_entry_point('apy', 'console_scripts', 'apy')()
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/skervim/apy/apy/cli.py", line 63, in add
    notes = a.add_notes_with_editor(tags, model, deck)
  File "/home/skervim/apy/apy/anki.py", line 322, in add_notes_with_editor
    return self.add_notes_from_file(tf.name)
  File "/home/skervim/apy/apy/anki.py", line 328, in add_notes_from_file
    tags)
  File "/home/skervim/apy/apy/anki.py", line 356, in add_notes_from_list
    note.get('deck')))
  File "/home/skervim/apy/apy/anki.py", line 389, in _add_note
    return Note(self, note)
  File "/home/skervim/apy/apy/note.py", line 11, in __init__
    self.fields = [x for x, y in self.n.items()]
  File "/home/skervim/anki/anki/notes.py", line 89, in items
    for ord, f in sorted(self._fmap.values())]
  File "/home/skervim/anki/anki/notes.py", line 89, in <listcomp>
    for ord, f in sorted(self._fmap.values())]
IndexError: list index out of range
```
Unfortunately, I couldn't find in the code why this happens, but I assume that chosen note type doesn't successfully override the last active note type and so `apy` tries to populate the last note type instead of the chosen one.

**Comment by skervim** [comment]
I think this bug is related to the following old issue: https://github.com/lervag/apy/issues/2
The reason why it only occured rarely was because 

1. I was mostly working on one note type. So it could only occur the few times I changed to another notetype 
2. I often first added cards of the "correct" note type in `anki desktop` and so there was no problem if I chose the same note type later with `apy`

**Comment by lervag** [comment]
I'm sorry, but I can't seem to reproduce this. Could you be more specific to what exactly you do to observe the problem?

**Comment by lervag** [comment]
Ok, I think I might have fixed it. Let me know if you still experience the issue!

**Comment by skervim** [comment]
Awesome! This solved the bug! It is now working fine :)

**Comment by lervag** [comment]
Great, happy to hear it :)
