### ISSUE TITLE
Attempt to change model (via review menu) results in crash

### ISSUE THREAD

**Issue by camoz** [lervag/apy#89]
When I do `apy review` and then press `N` to change the model, there is a warning saying that a new note will be created with a `y/n` prompt. If I then press `y` and enter, apy crashes with the following output:

```
Traceback (most recent call last):
  File "/home/merlin/.local/bin/apy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/apyanki/cli.py", line 387, in review
    if not note.review(i, number_of_notes):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/apyanki/note.py", line 523, in review
    if self.change_model():
       ^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/apyanki/note.py", line 257, in change_model
    index: int = console.prompt_int(">>> ", prompt_suffix="") - 1
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/apyanki/console.py", line 35, in prompt_int
    result = IntPrompt(console=self).ask(prompt, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PromptBase.ask() got an unexpected keyword argument 'prompt_suffix'

```

This is with apy 0.15.4 in bash.

**Comment by lervag** [comment]
I've pushed a fix to the `master` branch - it should be available as version 0.15.6.

**Comment by lervag** [comment]
Could you update and test if it works now?

**Comment by camoz** [comment]
Yes, I get the prompt for choosing a new model now, however if I press a number and then enter I get a new error:

```
Please choose new model:
  1: Basic
  2: Basic (and reversed card)
  3: Basic (optional reversed card)
  4: Basic (type in the answer)
  5: Cloze
  6: Image Occlusion
>>> 1
Traceback (most recent call last):
  File "/home/merlin/.local/bin/apy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/apyanki/cli.py", line 387, in review
    if not note.review(i, number_of_notes):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/apyanki/note.py", line 523, in review
    if self.change_model():
       ^^^^^^^^^^^^^^^^^^^
  File "/home/merlin/.local/share/pipx/venvs/apyanki/lib/python3.12/site-packages/apyanki/note.py", line 272, in change_model
    fields[field_name] = ""
    ~~~~~~^^^^^^^^^^^^
TypeError: unhashable type: 'dict'

```

Tried changing a Basic+reverse to Basic and changing a Basic to Cloze, both give an error...

**Comment by camoz** [comment]
Btw, I did not really provide any reproduction steps. If you can't instantly reproduce please let me know and I'll try to test more and come up with exact steps (exact notes I'm creating etc.).

**Comment by camoz** [comment]
Yes, can confirm that it works now (I have not tested all combinations), but converting to Cloze type does not. Should this issue stay open for the Cloze crash?

**Comment by lervag** [comment]
I've attempted to fix it. It's not perfect, but I think it fixes _most_ of the cases. So I'll close the issue now.

(Again, this is pushed to `master`, but it is not released quite yet.)
